name: Deploy to production

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-master-into-master_clever:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge master into master_clever
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: master_clever
          github_token: ${{ github.token }}