# This is a basic workflow to help you get started with Actions

name: Review apps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_NAME: itou-celinems
  CLEVER_CLI: ./clever-tools-latest_linux/clever
  CLEVER_DIR: clever-tools-latest_linux
  ORGANIZATION_NAME: Miimosa
  REVIEW_APP_NAME: $APP_NAME-$TRAVIS_BRANCH
  CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
  CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  delete-review-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Connect to Clever Cloud
      run: |
        echo "🛸 Build disposable staging"
        curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/$CLEVER_DIR.tar.gz > $CLEVER_DIR.tar.gz
        tar -xvf $CLEVER_DIR.tar.gz
        $CLEVER_CLI login --token $CLEVER_TOKEN --secret $CLEVER_SECRET

    - name: Delete review app
      run: |
        $CLEVER_CLI link $REVIEW_APP_NAME --org $ORGANIZATION_NAME
        $CLEVER_CLI delete --yes

  create-review-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: Create review app
      run: |
        $CLEVER_CLI create $REVIEW_APP_NAME -t docker --org $ORGANIZATION_NAME --region par --alias $REVIEW_APP_NAME
        $CLEVER_CLI domain add $REVIEW_APP_NAME.cleverapps.io --alias $REVIEW_APP_NAME
        $CLEVER_CLI published-config set <variable-name> <variable-value>
        $CLEVER_CLI --branch $TRAVIS_BRANCH deploy

