# This is a basic workflow to help you get started with Actions

name: Review apps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CLEVER_DIR: clever-tools-latest_linux
  CLEVER_CLI: clever-tools-latest_linux/clever
  ORGANIZATION_NAME: Miimosa
  REVIEW_APP_NAME: itou-celinems-${{ github.head_ref }}
  CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
  CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}


jobs:
  download-cc-binaries:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download CC binaries
        run: |
          curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > $CLEVER_DIR.tar.gz
          tar -xvf $CLEVER_DIR.tar.gz

      - uses: actions/upload-artifact@v1
        with:
          name: clever_cloud_bin
          path: .
  delete-review-app:
    needs: download-cc-binaries
    runs-on: ubuntu-latest

    steps:
    - name: Delete review app
      # curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/$CLEVER_DIR.tar.gz > $CLEVER_DIR.tar.gz
      # tar -xvf $CLEVER_DIR.tar.gz
      run: |
        $CLEVER_CLI login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        $CLEVER_CLI link $REVIEW_APP_NAME --org $ORGANIZATION_NAME
        $CLEVER_CLI delete --yes

    Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v1
      with:
        name: clever_cloud_bin
        path: .

      #  curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > $CLEVER_DIR.tar.gz
      #  tar -xvf $CLEVER_DIR.tar.gz
    - name: Connect to Clever Cloud
      run: |
        $CLEVER_CLI login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        $CLEVER_CLI applications


  create-review-app:
    runs-on: ubuntu-latest
    needs: delete-review-app
    if: always()

    steps:
    # Runs a set of commands using the runners shell
    #  curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > clever-tools-latest_linux.tar.gz
    #  tar -xvf clever-tools-latest_linux.tar.gz
    - name: Create review app
      run: |
        $CLEVER_CLI login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        $CLEVER_CLI create $REVIEW_APP_NAME -t docker --org $ORGANIZATION_NAME --region par --alias $REVIEW_APP_NAME
        $CLEVER_CLI domain add $REVIEW_APP_NAME.cleverapps.io --alias $REVIEW_APP_NAME
        # $CLEVER_CLI published-config set <variable-name> <variable-value>
        # $CLEVER_CLI --branch $TRAVIS_BRANCH deploy

