# This is a basic workflow to help you get started with Actions

name: Review apps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CLEVER_DIR: clever-tools-latest_linux
  CLEVER_CLI: $CLEVER_DIR/clever
  ORGANIZATION_NAME: Miimosa
  REVIEW_APP_NAME: itou-celinems-${{ github.sha }}
  CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
  CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  # download-cc-binaries:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Download CC binaries
  #       run: |
  #         mkdir clever_cloud_bin
  #         mkdir $CLEVER_DIR
  #         curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > $CLEVER_DIR.tar.gz
  #         tar -xvf $CLEVER_DIR.tar.gz

  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: clever_cloud_bin
  #         path: $CLEVER_DIR
jobs:
  delete-review-app:
    runs-on: ubuntu-latest

    steps:
    - name: Delete review app
      run: |
        curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > clever-tools-latest_linux.tar.gz
        tar -xvf clever-tools-latest_linux.tar.gz
        clever-tools-latest_linux/clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        clever-tools-latest_linux/clever link $REVIEW_APP_NAME --org $ORGANIZATION_NAME
        clever-tools-latest_linux/clever delete --yes
        echo 'LS'
        ls
        echo 'PWD'
        pwd
        echo 'CLEVER_DIR'
        echo $CLEVER_DIR

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2

    # - uses: actions/download-artifact@v1
    #   with:
    #     name: clever_cloud_bin

    # - name: Connect to Clever Cloud
    #   run: |
    #     curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > $CLEVER_DIR.tar.gz
    #     tar -xvf $CLEVER_DIR.tar.gz
    #     $CLEVER_CLI login --token $CLEVER_TOKEN --secret $CLEVER_SECRET


  create-review-app:
    runs-on: ubuntu-latest
    needs: delete-review-app
    if: always()

    steps:
    # Runs a set of commands using the runners shell
    - name: Create review app
      run: |
        curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > clever-tools-latest_linux.tar.gz
        tar -xvf clever-tools-latest_linux.tar.gz
        clever-tools-latest_linux/clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        clever-tools-latest_linux/clever create $REVIEW_APP_NAME -t docker --org $ORGANIZATION_NAME --region par --alias $REVIEW_APP_NAME
        clever-tools-latest_linux/clever domain add $REVIEW_APP_NAME.cleverapps.io --alias $REVIEW_APP_NAME
        $CLEVER_CLI published-config set <variable-name> <variable-value>
        $CLEVER_CLI --branch $TRAVIS_BRANCH deploy

